import type { Metadata } from "next";
import { SITE_URL, SITE_NAME } from "@/lib/site";
import { SiteHeader, SiteFooter } from "@/components/marketing/chrome";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `The terms for using ${SITE_NAME}.`,
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <SiteHeader />
      <article className="mx-auto max-w-2xl px-6 py-16">
        <h1 className="font-serif text-3xl font-semibold tracking-[-0.02em]">Terms of Service</h1>
        <p className="mt-2 text-sm text-ink-3">Last updated: July 2026</p>

        <div className="mt-4 rounded-md border border-amber-bg bg-amber-bg px-4 py-3 text-[13px] text-amber">
          This is a starting template. Review it with a legal professional and fill in your company
          and contact details before relying on it in production.
        </div>

        <div className="mt-8 flex flex-col gap-6 text-[15px] leading-relaxed text-ink-2 [&_h2]:mt-2 [&_h2]:font-serif [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-ink">
          <p>
            By using {SITE_NAME} you agree to these terms. If you don&apos;t agree, please
            don&apos;t use the service.
          </p>

          <div>
            <h2>The service</h2>
            <p>
              {SITE_NAME} lets you create, save, version, and run reusable AI prompts. We may change
              or improve features over time.
            </p>
          </div>

          <div>
            <h2>Your account</h2>
            <p>
              You&apos;re responsible for activity under your account and for keeping your sign-in
              secure.
            </p>
          </div>

          <div>
            <h2>Acceptable use</h2>
            <p>
              Don&apos;t use {SITE_NAME} for anything illegal, abusive, or infringing, don&apos;t
              attempt to disrupt or reverse-engineer the service, and don&apos;t resell it without
              permission. You&apos;re responsible for the content you generate and how you use it.
            </p>
          </div>

          <div>
            <h2>AI-generated content</h2>
            <p>
              Output is generated by AI models and may be inaccurate or unoriginal. Review it before
              you rely on or publish it. We make no guarantee of accuracy or fitness for a
              particular purpose.
            </p>
          </div>

          <div>
            <h2>Plans &amp; billing</h2>
            <p>
              Paid plans are billed monthly through Stripe and renew automatically until cancelled.
              You can cancel anytime from your account; access continues until the end of the paid
              period. Fees are non-refundable except where required by law.
            </p>
          </div>

          <div>
            <h2>Ownership</h2>
            <p>
              You own the prompts and outputs you create. We own the {SITE_NAME} platform, brand,
              and software.
            </p>
          </div>

          <div>
            <h2>Disclaimers &amp; liability</h2>
            <p>
              The service is provided &quot;as is&quot; without warranties. To the maximum extent
              permitted by law, we aren&apos;t liable for indirect or consequential damages, and our
              total liability is limited to the amount you paid us in the prior 12 months.
            </p>
          </div>

          <div>
            <h2>Termination &amp; changes</h2>
            <p>
              We may suspend accounts that violate these terms. We may update these terms; continued
              use means you accept the changes. Contact:{" "}
              <span className="font-mono text-[13px]">hello@promptpilot.app</span>.
            </p>
          </div>
        </div>
      </article>
      <SiteFooter />
    </div>
  );
}
